name: Release

# I use npm to store app version.
# When a new version is created

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: macos-latest
    permissions: write-all
    name: Release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: latest
      
      - name: Create ENV
        run: pnpx tsx .github/actions/env.ts
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: gitification-v__VERSION__
          releaseName: 'Gitification v__VERSION__'
          prerelease: false
          args: --target universal-apple-darwin